/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import javax.swing.table.TableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author rajan
 */
public class EditCourse extends javax.swing.JFrame {

   
    DefaultTableModel model = null;
    
    public EditCourse() {
        initComponents();
        setCourseOnTable();
    }
    
    public void setCourseOnTable(){
        try{
          Connection con = DBConnection.getMysqlConnection();
          PreparedStatement pst = con.prepareStatement("Select * from course");
          ResultSet rs = pst.executeQuery();
          
          while(rs.next()){
              String courseId = rs.getString("id");
              String courseName = rs.getString("cname");
              String courseCost = rs.getString("cost");
              
              Object[] obj = {courseId, courseName, courseCost};
              
              model = (DefaultTableModel)tblEditCourse.getModel();
              model.addRow(obj);                           
          }
          
          
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel)tblEditCourse.getModel();
        model.setRowCount(0);
    }
    public void addCourse(int id, String cname, double cost){
        try{
            Connection con = DBConnection.getMysqlConnection();
            PreparedStatement pst = con.prepareStatement("insert into course values(?, ?, ?)");
            pst.setInt(1, id);
            pst.setString(2, cname);
            pst.setDouble(3, cost);
            
            int rowCount = pst.executeUpdate();
            if(rowCount == 1){
                JOptionPane.showMessageDialog(this, "Course sccessfully added");
                clearTable(); // For clear table previous data
                setCourseOnTable(); // calling all the data from course table
            }
            else{
                JOptionPane.showMessageDialog(this, "Course adding fails");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Course adding fails");
            e.printStackTrace();
        }
    } 
    
    public void updateCourse(int id, String cname, double cost){
        try{
            Connection con = DBConnection.getMysqlConnection();
            PreparedStatement pst = con.prepareStatement("update course set cname = ?, cost = ? where id = ?");
            
            pst.setString(1, cname);
            pst.setDouble(2, cost);
            pst.setInt(3, id);
            
            int rowCount = pst.executeUpdate();
            if(rowCount == 1){
                JOptionPane.showMessageDialog(this, "Course sccessfully udated");
                clearTable(); // For clear table previous data
                setCourseOnTable(); // calling all the data from course table
            }
            else{
                JOptionPane.showMessageDialog(this, "Course updation fails");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Course updation fails");
            e.printStackTrace();
        }
    }
    
    public void deleteCourse(int id){
        try{
            Connection con = DBConnection.getMysqlConnection();
            PreparedStatement pst = con.prepareStatement("Delete from course where id = ?");
            
            pst.setInt(1, id);
            int rowCount = pst.executeUpdate();
            if(rowCount == 1){
                JOptionPane.showMessageDialog(this, "Course deleted successfully");
                
            }else{
                JOptionPane.showMessageDialog(this, "Course Deletion fails");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Course deletion fails");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_sr = new javax.swing.JButton();
        btn_cl = new javax.swing.JButton();
        btn_var = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_l = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditCourse = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCourseCost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        btnDeleteCourse = new javax.swing.JButton();
        btnAddCourse = new javax.swing.JButton();
        btnUpdateCourse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 151, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(52, 151, 219));
        btn_home.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), null, null, new java.awt.Color(0, 102, 255)));
        btn_home.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 260, 70));

        btn_sr.setBackground(new java.awt.Color(52, 151, 219));
        btn_sr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_sr.setForeground(new java.awt.Color(255, 255, 255));
        btn_sr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/search2.png"))); // NOI18N
        btn_sr.setText("Search Record");
        btn_sr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_sr.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_sr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_srMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_srMouseExited(evt);
            }
        });
        btn_sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_srActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 260, 70));

        btn_cl.setBackground(new java.awt.Color(52, 151, 219));
        btn_cl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_cl.setForeground(new java.awt.Color(255, 255, 255));
        btn_cl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/list_1.png"))); // NOI18N
        btn_cl.setText("Course List");
        btn_cl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_cl.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clMouseExited(evt);
            }
        });
        btn_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 260, 70));

        btn_var.setBackground(new java.awt.Color(52, 151, 219));
        btn_var.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_var.setForeground(new java.awt.Color(255, 255, 255));
        btn_var.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/view all record.png"))); // NOI18N
        btn_var.setText("View All Record");
        btn_var.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_var.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_var.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_varMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_varMouseExited(evt);
            }
        });
        btn_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_varActionPerformed(evt);
            }
        });
        jPanel1.add(btn_var, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 260, 70));

        btn_b.setBackground(new java.awt.Color(52, 151, 219));
        btn_b.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_b.setForeground(new java.awt.Color(255, 255, 255));
        btn_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/left-arrow.png"))); // NOI18N
        btn_b.setText("Back");
        btn_b.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_b.setMargin(new java.awt.Insets(0, -10, 1, 25));
        btn_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bMouseExited(evt);
            }
        });
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });
        jPanel1.add(btn_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 260, 70));

        btn_l.setBackground(new java.awt.Color(52, 151, 219));
        btn_l.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_l.setForeground(new java.awt.Color(255, 255, 255));
        btn_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/logout.png"))); // NOI18N
        btn_l.setText("Log Out");
        btn_l.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_l.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lMouseExited(evt);
            }
        });
        btn_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lActionPerformed(evt);
            }
        });
        jPanel1.add(btn_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 260, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 370, 690));

        tblEditCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Course Cost"
            }
        ));
        tblEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEditCourse);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 610, 580));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Course Cost :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 120, 20));

        txtCourseCost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCourseCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseCostActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Course Id :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Course Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, 20));

        txtCourseId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCourseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, -1));

        txtCourseName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, -1));

        btnDeleteCourse.setBackground(new java.awt.Color(255, 102, 102));
        btnDeleteCourse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDeleteCourse.setText("Delete");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        btnAddCourse.setBackground(new java.awt.Color(255, 102, 102));
        btnAddCourse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAddCourse.setText("Add");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        btnUpdateCourse.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdateCourse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnUpdateCourse.setText("Update");
        btnUpdateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCourseActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        Color clr = new Color(56,149,242);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        Color clr = new Color(52,151,217);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_srMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseEntered
        Color clr = new Color(56,149,242);
        btn_sr.setBackground(clr);
    }//GEN-LAST:event_btn_srMouseEntered

    private void btn_srMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseExited
        Color clr = new Color(52,151,217);
        btn_sr.setBackground(clr);
    }//GEN-LAST:event_btn_srMouseExited

    private void btn_srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_srActionPerformed
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_srActionPerformed

    private void btn_clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseEntered
        Color clr = new Color(56,149,242);
        btn_cl.setBackground(clr);
    }//GEN-LAST:event_btn_clMouseEntered

    private void btn_clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseExited
        Color clr = new Color(52,151,217);
        btn_cl.setBackground(clr);
    }//GEN-LAST:event_btn_clMouseExited

    private void btn_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clActionPerformed
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_clActionPerformed

    private void btn_varMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_varMouseEntered
        Color clr = new Color(56,149,242);
        btn_var.setBackground(clr);
    }//GEN-LAST:event_btn_varMouseEntered

    private void btn_varMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_varMouseExited
        Color clr = new Color(52,151,217);
        btn_var.setBackground(clr);
    }//GEN-LAST:event_btn_varMouseExited

    private void btn_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_varActionPerformed
        ViewAllRecord var = new ViewAllRecord();
        var.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_varActionPerformed

    private void btn_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseEntered
        Color clr = new Color(56,149,242);
        btn_b.setBackground(clr);
    }//GEN-LAST:event_btn_bMouseEntered

    private void btn_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseExited
        Color clr = new Color(52,151,217);
        btn_b.setBackground(clr);
    }//GEN-LAST:event_btn_bMouseExited

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_lMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseEntered
        Color clr = new Color(56,149,242);
        btn_l.setBackground(clr);
    }//GEN-LAST:event_btn_lMouseEntered

    private void btn_lMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseExited
        Color clr = new Color(52,151,217);
        btn_l.setBackground(clr);
    }//GEN-LAST:event_btn_lMouseExited

    private void btn_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lActionPerformed
        LogIn li = new LogIn();
        li.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_lActionPerformed

    private void txtCourseCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseCostActionPerformed

    private void txtCourseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseIdActionPerformed

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void tblEditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditCourseMouseClicked
       int rowNo = tblEditCourse.getSelectedRow();
       TableModel tbl = tblEditCourse.getModel();
       
       txtCourseId.setText(tbl.getValueAt(rowNo, 0).toString());
       txtCourseName.setText(tbl.getValueAt(rowNo, 1).toString());
       txtCourseCost.setText(tbl.getValueAt(rowNo, 2).toString());
    }//GEN-LAST:event_tblEditCourseMouseClicked

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        int id = Integer.parseInt(txtCourseId.getText());
        deleteCourse(id);
        clearTable();
        setCourseOnTable();
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        int id = Integer.parseInt(txtCourseId.getText());
        String cname = txtCourseName.getText();
        double cost = Double.parseDouble(txtCourseCost.getText());
        
        addCourse(id, cname, cost);
        
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnUpdateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCourseActionPerformed
        int id = Integer.parseInt(txtCourseId.getText());
        String cname = txtCourseName.getText();
        double cost = Double.parseDouble(txtCourseCost.getText());
        
        updateCourse(id, cname, cost);
        
    }//GEN-LAST:event_btnUpdateCourseActionPerformed

    private void btn_clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseClicked
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_clMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnUpdateCourse;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_cl;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_l;
    private javax.swing.JButton btn_sr;
    private javax.swing.JButton btn_var;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEditCourse;
    private javax.swing.JTextField txtCourseCost;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtCourseName;
    // End of variables declaration//GEN-END:variables
}
