/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;

/**
 *
 * @author rajan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        lbl_add_fee = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        lbl_search_record = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        lbl_view_record = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        lbl_edit_record = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        lbl_view_course = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        lbl_view_report = new javax.swing.JLabel();
        panel7 = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        panel8 = new javax.swing.JPanel();
        lbl_about = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 151, 217));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Fees Management System");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Makhanlal Chaturvedi National University");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panel1.setBackground(new java.awt.Color(52, 151, 217));
        panel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 255), 1, true));
        panel1.setPreferredSize(new java.awt.Dimension(200, 130));
        panel1.setRequestFocusEnabled(false);
        panel1.setVerifyInputWhenFocusTarget(false);
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel1MouseExited(evt);
            }
        });

        lbl_add_fee.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_add_fee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_add_fee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/plus.png"))); // NOI18N
        lbl_add_fee.setText("     Add fees");
        lbl_add_fee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_add_fee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_add_feeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_add_feeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_add_feeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(lbl_add_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_add_fee, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        panel2.setBackground(new java.awt.Color(52, 151, 217));
        panel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 255), 1, true));
        panel2.setPreferredSize(new java.awt.Dimension(200, 130));
        panel2.setRequestFocusEnabled(false);
        panel2.setVerifyInputWhenFocusTarget(false);
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel2MouseEntered(evt);
            }
        });

        lbl_search_record.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_search_record.setForeground(new java.awt.Color(255, 255, 255));
        lbl_search_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/search-document.png"))); // NOI18N
        lbl_search_record.setText("Search Record");
        lbl_search_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_search_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_search_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_search_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_search_recordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(lbl_search_record, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_search_record, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        panel3.setBackground(new java.awt.Color(52, 151, 217));
        panel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 255), 1, true));
        panel3.setPreferredSize(new java.awt.Dimension(200, 130));
        panel3.setRequestFocusEnabled(false);
        panel3.setVerifyInputWhenFocusTarget(false);

        lbl_view_record.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_view_record.setForeground(new java.awt.Color(255, 255, 255));
        lbl_view_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/view all record.png"))); // NOI18N
        lbl_view_record.setText("   View Record");
        lbl_view_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_view_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_view_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_view_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_view_recordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(lbl_view_record, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_view_record, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        panel4.setBackground(new java.awt.Color(52, 151, 217));
        panel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 255), 1, true));
        panel4.setPreferredSize(new java.awt.Dimension(200, 130));
        panel4.setRequestFocusEnabled(false);
        panel4.setVerifyInputWhenFocusTarget(false);

        lbl_edit_record.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_edit_record.setForeground(new java.awt.Color(255, 255, 255));
        lbl_edit_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/edit.png"))); // NOI18N
        lbl_edit_record.setText("Edit Course");
        lbl_edit_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_edit_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_edit_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_edit_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_edit_recordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(lbl_edit_record, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_edit_record, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        panel5.setBackground(new java.awt.Color(52, 151, 217));
        panel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 255), 1, true));
        panel5.setPreferredSize(new java.awt.Dimension(200, 130));
        panel5.setRequestFocusEnabled(false);
        panel5.setVerifyInputWhenFocusTarget(false);

        lbl_view_course.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_view_course.setForeground(new java.awt.Color(255, 255, 255));
        lbl_view_course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/text-book-opened-from-top-view.png"))); // NOI18N
        lbl_view_course.setText("  View Course");
        lbl_view_course.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_view_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_view_courseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_view_courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_view_courseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(lbl_view_course, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_view_course, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        panel6.setBackground(new java.awt.Color(52, 151, 217));
        panel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 255), 1, true));
        panel6.setPreferredSize(new java.awt.Dimension(200, 130));
        panel6.setRequestFocusEnabled(false);
        panel6.setVerifyInputWhenFocusTarget(false);

        lbl_view_report.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_view_report.setForeground(new java.awt.Color(255, 255, 255));
        lbl_view_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/view report.png"))); // NOI18N
        lbl_view_report.setText("  View Report");
        lbl_view_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_view_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_view_reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_view_reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_view_reportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(lbl_view_report, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_view_report, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        panel7.setBackground(new java.awt.Color(52, 151, 217));
        panel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 255), 1, true));
        panel7.setPreferredSize(new java.awt.Dimension(200, 130));
        panel7.setRequestFocusEnabled(false);
        panel7.setVerifyInputWhenFocusTarget(false);

        lbl_logout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/logout.png"))); // NOI18N
        lbl_logout.setText("Log Out");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_logout)
                .addContainerGap())
        );

        panel8.setBackground(new java.awt.Color(52, 151, 217));
        panel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 255), 1, true));
        panel8.setPreferredSize(new java.awt.Dimension(200, 130));
        panel8.setRequestFocusEnabled(false);
        panel8.setVerifyInputWhenFocusTarget(false);

        lbl_about.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_about.setForeground(new java.awt.Color(255, 255, 255));
        lbl_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/about.png"))); // NOI18N
        lbl_about.setText("  About");
        lbl_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_about, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(panel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1080, 610));

        setSize(new java.awt.Dimension(1094, 724));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_add_feeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_add_feeMouseEntered
        Color clr = new Color(56,149,242);
        panel1.setBackground(clr); 
    }//GEN-LAST:event_lbl_add_feeMouseEntered

    private void panel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseEntered
          
    }//GEN-LAST:event_panel1MouseEntered

    private void panel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseExited
       
    }//GEN-LAST:event_panel1MouseExited

    private void lbl_search_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_search_recordMouseExited
        Color clr = new Color(52,151,217);
        panel2.setBackground(clr);
    }//GEN-LAST:event_lbl_search_recordMouseExited

    private void lbl_search_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_search_recordMouseEntered
        Color clr = new Color(56,149,242);
        panel2.setBackground(clr); 
    }//GEN-LAST:event_lbl_search_recordMouseEntered

    private void lbl_add_feeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_add_feeMouseExited
         Color clr = new Color(52,151,217);
        panel1.setBackground(clr);
    }//GEN-LAST:event_lbl_add_feeMouseExited

    private void panel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseEntered
        
    }//GEN-LAST:event_panel2MouseEntered

    private void lbl_view_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_recordMouseEntered
        Color clr = new Color(56,149,242);
        panel3.setBackground(clr); 
    }//GEN-LAST:event_lbl_view_recordMouseEntered

    private void lbl_view_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_recordMouseExited
       Color clr = new Color(52,151,217);
        panel3.setBackground(clr);
    }//GEN-LAST:event_lbl_view_recordMouseExited

    private void lbl_edit_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_edit_recordMouseEntered
        Color clr = new Color(56,149,242);
        panel4.setBackground(clr); 
    }//GEN-LAST:event_lbl_edit_recordMouseEntered

    private void lbl_edit_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_edit_recordMouseExited
        Color clr = new Color(52,151,217);
        panel4.setBackground(clr);
    }//GEN-LAST:event_lbl_edit_recordMouseExited

    private void lbl_view_courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_courseMouseEntered
       Color clr = new Color(56,149,242);
        panel5.setBackground(clr); 
    }//GEN-LAST:event_lbl_view_courseMouseEntered

    private void lbl_view_courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_courseMouseExited
        Color clr = new Color(52,151,217);
        panel5.setBackground(clr);
    }//GEN-LAST:event_lbl_view_courseMouseExited

    private void lbl_view_reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_reportMouseEntered
        Color clr = new Color(56,149,242);
        panel6.setBackground(clr); 
    }//GEN-LAST:event_lbl_view_reportMouseEntered

    private void lbl_view_reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_reportMouseExited
        Color clr = new Color(52,151,217);
        panel6.setBackground(clr);
    }//GEN-LAST:event_lbl_view_reportMouseExited

    private void lbl_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseEntered
       Color clr = new Color(56,149,242);
        panel7.setBackground(clr); 
    }//GEN-LAST:event_lbl_logoutMouseEntered

    private void lbl_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseExited
        Color clr = new Color(52,151,217);
        panel7.setBackground(clr);
    }//GEN-LAST:event_lbl_logoutMouseExited

    private void lbl_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseEntered
        Color clr = new Color(56,149,242);
        panel8.setBackground(clr); 
    }//GEN-LAST:event_lbl_aboutMouseEntered

    private void lbl_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseExited
       Color clr = new Color(52,151,217);
        panel8.setBackground(clr);
    }//GEN-LAST:event_lbl_aboutMouseExited

    private void lbl_add_feeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_add_feeMouseClicked
        AddFees af = new AddFees();
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_add_feeMouseClicked

    private void lbl_search_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_search_recordMouseClicked
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_search_recordMouseClicked

    private void lbl_edit_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_edit_recordMouseClicked
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_edit_recordMouseClicked

    private void lbl_view_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_recordMouseClicked
        ViewAllRecord vr = new ViewAllRecord();
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_view_recordMouseClicked

    private void lbl_view_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_reportMouseClicked
        ViewReport vr = new ViewReport();
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_view_reportMouseClicked

    private void lbl_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseClicked
        CopyRightPage cr = new CopyRightPage();
        cr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_aboutMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        LogIn li = new LogIn();
        li.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void lbl_view_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_view_courseMouseClicked
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_view_courseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_about;
    private javax.swing.JLabel lbl_add_fee;
    private javax.swing.JLabel lbl_edit_record;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_search_record;
    private javax.swing.JLabel lbl_view_course;
    private javax.swing.JLabel lbl_view_record;
    private javax.swing.JLabel lbl_view_report;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JPanel panel8;
    // End of variables declaration//GEN-END:variables
}
