
package fees_management_system;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author rajan
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecords();
    }
    
    public void getRecords(){
        try{
           Connection  con = DBConnection.getMysqlConnection();
           PreparedStatement pst = con.prepareStatement("select * from fees_details order by reciept_no desc limit 1");
           ResultSet rs = pst.executeQuery();
           rs.next();
           recieptNo.setText(rs.getString("reciept_no"));
           paymentMode.setText(rs.getString("payment_mode"));
           
           String payment = rs.getString("payment_mode");
           
           if(payment.equalsIgnoreCase("cheque")){
               lbl_cheque_dd.setText("Cheque No :");
               cheque_dd_no.setText(rs.getString("cheque_no"));
               bankName.setText(rs.getString("bank_Name"));
           }
           
           if(payment.equalsIgnoreCase("card")){
               lbl_cheque_dd.setText("Card Number");
               cheque_dd_no.setText("Not Required");
               bankName.setText(rs.getString("bank_name"));
           }
           
           if(payment.equalsIgnoreCase("dd")){
               lbl_cheque_dd.setText("DD No :");
               cheque_dd_no.setText(rs.getString("dd_no"));
               bankName.setText(rs.getString("bank_name")); 
           }
           
           if(payment.equalsIgnoreCase("cash")){
               lbl_cheque_dd.setText(" ");
               cheque_dd_no.setText(" ");
               bankName.setText("NA"); 
           }
           
           recievedFrom.setText(rs.getString("student_name"));
           txtDate.setText(rs.getString("date"));
           gstinNo.setText(rs.getString("gstin"));
           year1.setText(rs.getString("year1"));
           year2.setText(rs.getString("year2"));
           
           srNo.setText(rs.getString("reciept_no"));
           
           head.setText(rs.getString("course_name"));
           txtRs.setText(rs.getString("amount"));
           cgst.setText(rs.getString("cgst"));
           sgst.setText(rs.getString("sgst"));
           totalRs.setText(rs.getString("total_amount"));
           rsInWords.setText(rs.getString("Total_in_words"));
           
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_sr = new javax.swing.JButton();
        btn_ec = new javax.swing.JButton();
        btn_cl = new javax.swing.JButton();
        btn_var = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_l = new javax.swing.JButton();
        btn_l1 = new javax.swing.JButton();
        btn_l2 = new javax.swing.JButton();
        print_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        year1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        year2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        gstinNo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        lblCgst = new javax.swing.JLabel();
        lblSgst = new javax.swing.JLabel();
        txtRs = new javax.swing.JLabel();
        cgst = new javax.swing.JLabel();
        sgst = new javax.swing.JLabel();
        srNo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        recieptNo = new javax.swing.JLabel();
        paymentMode = new javax.swing.JLabel();
        bankName = new javax.swing.JLabel();
        cheque_dd_no = new javax.swing.JLabel();
        recievedFrom = new javax.swing.JLabel();
        totalRs = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        rsInWords = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(52, 151, 217));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(52, 151, 219));
        btn_home.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), null, null, new java.awt.Color(0, 102, 255)));
        btn_home.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 70));

        btn_sr.setBackground(new java.awt.Color(52, 151, 219));
        btn_sr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_sr.setForeground(new java.awt.Color(255, 255, 255));
        btn_sr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/search2.png"))); // NOI18N
        btn_sr.setText("Search Record");
        btn_sr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_sr.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_sr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_srMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_srMouseExited(evt);
            }
        });
        btn_sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_srActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 260, 70));

        btn_ec.setBackground(new java.awt.Color(52, 151, 219));
        btn_ec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_ec.setForeground(new java.awt.Color(255, 255, 255));
        btn_ec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/edit2.png"))); // NOI18N
        btn_ec.setText("Edit Course");
        btn_ec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_ec.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_ec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ecMouseExited(evt);
            }
        });
        btn_ec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ecActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ec, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 260, 70));

        btn_cl.setBackground(new java.awt.Color(52, 151, 219));
        btn_cl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_cl.setForeground(new java.awt.Color(255, 255, 255));
        btn_cl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/list_1.png"))); // NOI18N
        btn_cl.setText("Course List");
        btn_cl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_cl.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clMouseExited(evt);
            }
        });
        btn_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 260, 70));

        btn_var.setBackground(new java.awt.Color(52, 151, 219));
        btn_var.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_var.setForeground(new java.awt.Color(255, 255, 255));
        btn_var.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/view all record.png"))); // NOI18N
        btn_var.setText("View All Record");
        btn_var.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_var.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_var.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_varMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_varMouseExited(evt);
            }
        });
        btn_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_varActionPerformed(evt);
            }
        });
        jPanel2.add(btn_var, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 260, 70));

        btn_b.setBackground(new java.awt.Color(52, 151, 219));
        btn_b.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_b.setForeground(new java.awt.Color(255, 255, 255));
        btn_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/left-arrow.png"))); // NOI18N
        btn_b.setText("Back");
        btn_b.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_b.setMargin(new java.awt.Insets(0, -10, 1, 25));
        btn_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bMouseExited(evt);
            }
        });
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });
        jPanel2.add(btn_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 260, 70));

        btn_l.setBackground(new java.awt.Color(52, 151, 219));
        btn_l.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_l.setForeground(new java.awt.Color(255, 255, 255));
        btn_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/logout.png"))); // NOI18N
        btn_l.setText("Log Out");
        btn_l.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_l.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lMouseExited(evt);
            }
        });
        btn_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lActionPerformed(evt);
            }
        });
        jPanel2.add(btn_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 260, 70));

        btn_l1.setBackground(new java.awt.Color(52, 151, 219));
        btn_l1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_l1.setForeground(new java.awt.Color(255, 255, 255));
        btn_l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/printer-.png"))); // NOI18N
        btn_l1.setText("   Print");
        btn_l1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_l1.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_l1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_l1MouseExited(evt);
            }
        });
        btn_l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_l1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 740, 260, 70));

        btn_l2.setBackground(new java.awt.Color(52, 151, 219));
        btn_l2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_l2.setForeground(new java.awt.Color(255, 255, 255));
        btn_l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/edit2.png"))); // NOI18N
        btn_l2.setText("    Edit");
        btn_l2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_l2.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_l2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_l2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_l2MouseExited(evt);
            }
        });
        btn_l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_l2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 260, 70));

        print_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Reciept No. :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Payment Mode :");

        lbl_cheque_dd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_cheque_dd.setText("Cheque_dd");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Bank Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Recieved From :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("The Following payment in the college in the year ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Sr. No.");

        year1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        year1.setText("2022");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("-");

        year2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        year2.setText("2023");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Date :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("GSTIN :");

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDate.setText("Date :");

        gstinNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gstinNo.setText("GSTIN :");

        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Head");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Amount");

        head.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        head.setText("Head");

        lblCgst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCgst.setText("CGST 9%");

        lblSgst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSgst.setText("SGST 9%");

        txtRs.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtRs.setText("Initial-Amount");

        cgst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cgst.setText("CGST");

        sgst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sgst.setText("SGST");

        srNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        srNo.setText("1");

        jSeparator3.setBackground(new java.awt.Color(0, 204, 255));

        recieptNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        recieptNo.setText("Reciept No. :");

        paymentMode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        paymentMode.setText("Payment Mode :");

        bankName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bankName.setText("Bank Name :");

        cheque_dd_no.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cheque_dd_no.setText("Cheque No_DD");

        recievedFrom.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        recievedFrom.setText("Recieved From :");

        totalRs.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalRs.setText("totalRs");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setText("Total Amount :");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel31.setText("Total Amount In Words :");

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));

        rsInWords.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rsInWords.setText(" ");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Signature");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel34.setText("Makhanlal Chaturvedi National University");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel35.setText("of Journalisma & Communication Bhopal Madhya Pradesh");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/mcuLogo_4.png"))); // NOI18N

        javax.swing.GroupLayout print_panelLayout = new javax.swing.GroupLayout(print_panel);
        print_panel.setLayout(print_panelLayout);
        print_panelLayout.setHorizontalGroup(
            print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(print_panelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recieptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recievedFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addComponent(lbl_cheque_dd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cheque_dd_no, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, print_panelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentMode))
                            .addGroup(print_panelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(year1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(38, 38, 38)
                        .addComponent(txtDate))
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(gstinNo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
            .addGroup(print_panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(print_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(print_panelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(srNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSgst)
                        .addComponent(lblCgst))
                    .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cgst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sgst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRs, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(print_panelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_panelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_panelLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(212, 212, 212))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_panelLayout.createSequentialGroup()
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(totalRs, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_panelLayout.createSequentialGroup()
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(186, 186, 186)))))
            .addGroup(print_panelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(print_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(print_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(rsInWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        print_panelLayout.setVerticalGroup(
            print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(print_panelLayout.createSequentialGroup()
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(txtDate)
                    .addComponent(recieptNo))
                .addGap(28, 28, 28)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(gstinNo)
                    .addComponent(paymentMode))
                .addGap(18, 18, 18)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cheque_dd)
                    .addComponent(cheque_dd_no))
                .addGap(18, 18, 18)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bankName))
                .addGap(18, 18, 18)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(recievedFrom))
                .addGap(18, 18, 18)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(year1)
                    .addComponent(jLabel9)
                    .addComponent(year2))
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(head)
                            .addComponent(srNo)))
                    .addGroup(print_panelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtRs)))
                .addGap(20, 20, 20)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCgst)
                    .addComponent(cgst))
                .addGap(18, 18, 18)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSgst)
                    .addComponent(sgst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(totalRs))
                .addGap(54, 54, 54)
                .addGroup(print_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rsInWords)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addGap(44, 44, 44))
        );

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel37.setText("Print Reciept");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(print_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(448, 448, 448))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel37)
                        .addGap(27, 27, 27)
                        .addComponent(print_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 90, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1480, 860));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        Color clr = new Color(56,149,242);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        Color clr = new Color(52,151,217);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_srMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseEntered
        Color clr = new Color(56,149,242);
        btn_sr.setBackground(clr);
    }//GEN-LAST:event_btn_srMouseEntered

    private void btn_srMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseExited
        Color clr = new Color(52,151,217);
        btn_sr.setBackground(clr);
    }//GEN-LAST:event_btn_srMouseExited

    private void btn_srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_srActionPerformed
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_srActionPerformed

    private void btn_ecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseEntered
        Color clr = new Color(56,149,242);
        btn_ec.setBackground(clr);
    }//GEN-LAST:event_btn_ecMouseEntered

    private void btn_ecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseExited
        Color clr = new Color(52,151,217);
        btn_ec.setBackground(clr);
    }//GEN-LAST:event_btn_ecMouseExited

    private void btn_ecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ecActionPerformed
        EditCourse ec =new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ecActionPerformed

    private void btn_clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseEntered
        Color clr = new Color(56,149,242);
        btn_cl.setBackground(clr);
    }//GEN-LAST:event_btn_clMouseEntered

    private void btn_clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseExited
        Color clr = new Color(52,151,217);
        btn_cl.setBackground(clr);
    }//GEN-LAST:event_btn_clMouseExited

    private void btn_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clActionPerformed
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_clActionPerformed

    private void btn_varMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_varMouseEntered
        Color clr = new Color(56,149,242);
        btn_var.setBackground(clr);
    }//GEN-LAST:event_btn_varMouseEntered

    private void btn_varMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_varMouseExited
        Color clr = new Color(52,151,217);
        btn_var.setBackground(clr);
    }//GEN-LAST:event_btn_varMouseExited

    private void btn_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_varActionPerformed
        ViewAllRecord var = new ViewAllRecord();
        var.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_varActionPerformed

    private void btn_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseEntered
        Color clr = new Color(56,149,242);
        btn_b.setBackground(clr);
    }//GEN-LAST:event_btn_bMouseEntered

    private void btn_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseExited
        Color clr = new Color(52,151,217);
        btn_b.setBackground(clr);
    }//GEN-LAST:event_btn_bMouseExited

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_lMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseEntered
        Color clr = new Color(56,149,242);
        btn_l.setBackground(clr);
    }//GEN-LAST:event_btn_lMouseEntered

    private void btn_lMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseExited
        Color clr = new Color(52,151,217);
        btn_l.setBackground(clr);
    }//GEN-LAST:event_btn_lMouseExited

    private void btn_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lActionPerformed
        LogIn li = new LogIn();
        li.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_lActionPerformed

    private void btn_l1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_l1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_l1MouseEntered

    private void btn_l1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_l1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_l1MouseExited

    private void btn_l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_l1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_l1ActionPerformed

    private void btn_l2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_l2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_l2MouseEntered

    private void btn_l2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_l2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_l2MouseExited

    private void btn_l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_l2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_l2ActionPerformed

    private void btn_l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_l1MouseClicked
        
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        
        job.setPrintable(new Printable(){
            
            @Override
            public int print(Graphics pg, PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D q2 = (Graphics2D)pg;
                q2.translate(pf.getImageableX(), pf.getImageableY());
                q2.scale(0.47, 0.47);
                
                print_panel.print(q2);
                
                return Printable.PAGE_EXISTS;
            }
        
        
            });
        boolean ok = job.printDialog();
        if(ok){
            try
            {
               job.print();
            }
            catch(PrinterException ex)
            {
                ex.printStackTrace();
            }
        }
        
        
    }//GEN-LAST:event_btn_l1MouseClicked

    private void btn_l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_l2MouseClicked
        UpdateFeesDetails ufd = new UpdateFeesDetails();
        ufd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_l2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankName;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_cl;
    private javax.swing.JButton btn_ec;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_l;
    private javax.swing.JButton btn_l1;
    private javax.swing.JButton btn_l2;
    private javax.swing.JButton btn_sr;
    private javax.swing.JButton btn_var;
    private javax.swing.JLabel cgst;
    private javax.swing.JLabel cheque_dd_no;
    private javax.swing.JLabel gstinNo;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCgst;
    private javax.swing.JLabel lblSgst;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JLabel paymentMode;
    private javax.swing.JPanel print_panel;
    private javax.swing.JLabel recieptNo;
    private javax.swing.JLabel recievedFrom;
    private javax.swing.JLabel rsInWords;
    private javax.swing.JLabel sgst;
    private javax.swing.JLabel srNo;
    private javax.swing.JLabel totalRs;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtRs;
    private javax.swing.JLabel year1;
    private javax.swing.JLabel year2;
    // End of variables declaration//GEN-END:variables
}
