
package fees_management_system;

import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author rajan
 */
public class ViewReport extends javax.swing.JFrame {

    DefaultTableModel model = null;
    
    public ViewReport() {
        initComponents();
        fillCourse();
        
    }
    
    public void fillCourse(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management","root", "0170");
            PreparedStatement pst = con.prepareStatement("Select cname from course");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                comboCourse.addItem(rs.getString("cname"));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void setRecordToTable(){
        
        Float totalAmount = 0f;
        
        String cname = comboCourse.getSelectedItem().toString();
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String dateFrom = dateFormat.format(fromDate.getDate());
        String dateTo = dateFormat.format(toDate.getDate());
        
        
        
        try{
            Connection con = DBConnection.getMysqlConnection();
            PreparedStatement pst = con.prepareStatement("Select * from fees_details where date between ? and ? and course_name = ? ");
            
            pst.setString(1, dateFrom);
            pst.setString(2, dateTo);
            pst.setString(3, cname);
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String recieptNo = rs.getString("reciept_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("course_name");
                float amount = rs.getFloat("total_amount");
//                String amount = rs.getString("total_amount");
//                String date = rs.getDate("date").toString();
                String remark = rs.getString("remarks");
                
                totalAmount = totalAmount + amount;
                
                Object[] obj = {recieptNo, rollNo, studentName, courseName, amount,remark};
                
                model = (DefaultTableModel)tblViewReport.getModel();
                model.addRow(obj);
                
                selectedCourse.setText(courseName);
                totalAmountCollect.setText(totalAmount.toString());
                totalAmountInWord.setText(NumberToWordsConverter.convert(totalAmount.intValue()));
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel)tblViewReport.getModel();
        model.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_sr = new javax.swing.JButton();
        btn_ec = new javax.swing.JButton();
        btn_cl = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_l = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        comboCourse = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        btnSubmit = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        selectedCourse = new javax.swing.JLabel();
        totalAmountCollect = new javax.swing.JLabel();
        totalAmountInWord = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 151, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(52, 151, 219));
        btn_home.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), null, null, new java.awt.Color(0, 102, 255)));
        btn_home.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 260, 70));

        btn_sr.setBackground(new java.awt.Color(52, 151, 219));
        btn_sr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_sr.setForeground(new java.awt.Color(255, 255, 255));
        btn_sr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/search2.png"))); // NOI18N
        btn_sr.setText("Search Record");
        btn_sr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_sr.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_sr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_srMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_srMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_srMouseExited(evt);
            }
        });
        btn_sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_srActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 260, 70));

        btn_ec.setBackground(new java.awt.Color(52, 151, 219));
        btn_ec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_ec.setForeground(new java.awt.Color(255, 255, 255));
        btn_ec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/edit2.png"))); // NOI18N
        btn_ec.setText("Edit Course");
        btn_ec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_ec.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_ec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ecMouseExited(evt);
            }
        });
        btn_ec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ecActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 260, 70));

        btn_cl.setBackground(new java.awt.Color(52, 151, 219));
        btn_cl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_cl.setForeground(new java.awt.Color(255, 255, 255));
        btn_cl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/list_1.png"))); // NOI18N
        btn_cl.setText("Course List");
        btn_cl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_cl.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clMouseExited(evt);
            }
        });
        btn_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 260, 70));

        btn_b.setBackground(new java.awt.Color(52, 151, 219));
        btn_b.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_b.setForeground(new java.awt.Color(255, 255, 255));
        btn_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/left-arrow.png"))); // NOI18N
        btn_b.setText("Back");
        btn_b.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_b.setMargin(new java.awt.Insets(0, -10, 1, 25));
        btn_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bMouseExited(evt);
            }
        });
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });
        jPanel1.add(btn_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 260, 70));

        btn_l.setBackground(new java.awt.Color(52, 151, 219));
        btn_l.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_l.setForeground(new java.awt.Color(255, 255, 255));
        btn_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/logout.png"))); // NOI18N
        btn_l.setText("Log Out");
        btn_l.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_l.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lMouseExited(evt);
            }
        });
        btn_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lActionPerformed(evt);
            }
        });
        jPanel1.add(btn_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 260, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/back1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 760));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Select Course :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 25));

        txtFilePath.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilePathActionPerformed(evt);
            }
        });
        jPanel2.add(txtFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 208, 209, -1));

        comboCourse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseActionPerformed(evt);
            }
        });
        jPanel2.add(comboCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 288, 25));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Select Date :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 25));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("From Date :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 97, 25));

        fromDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 160, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("To Date :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 70, 25));

        toDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 160, 25));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 154, -1, -1));

        btnPrint.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 154, -1, -1));

        btnBrowse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        jPanel2.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 208, -1, -1));

        btnExport.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnExport.setText("Export to excel");
        jPanel2.add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 208, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Course Selected :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Total Amount Collected : ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Total Amount In Words : ");

        selectedCourse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        totalAmountCollect.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        totalAmountInWord.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalAmountCollect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(totalAmountInWord, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectedCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalAmountCollect, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalAmountInWord, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 460, -1));

        tblViewReport.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblViewReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Reciept No", "Roll NO", "Student Name", "Course", "Amount", "Remark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewReport);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 294, 1140, 470));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 1160, 830));

        setSize(new java.awt.Dimension(1541, 820));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        Color clr = new Color(56,149,242);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        Color clr = new Color(52,151,217);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_srMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseClicked
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_srMouseClicked

    private void btn_srMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseEntered
        Color clr = new Color(56,149,242);
        btn_sr.setBackground(clr);
    }//GEN-LAST:event_btn_srMouseEntered

    private void btn_srMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseExited
        Color clr = new Color(52,151,217);
        btn_sr.setBackground(clr);
    }//GEN-LAST:event_btn_srMouseExited

    private void btn_srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_srActionPerformed
        SearchRecord sc = new SearchRecord();
        sc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_srActionPerformed

    private void btn_ecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseClicked
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ecMouseClicked

    private void btn_ecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseEntered
        Color clr = new Color(56,149,242);
        btn_ec.setBackground(clr);
    }//GEN-LAST:event_btn_ecMouseEntered

    private void btn_ecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseExited
        Color clr = new Color(52,151,217);
        btn_ec.setBackground(clr);
    }//GEN-LAST:event_btn_ecMouseExited

    private void btn_ecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ecActionPerformed
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ecActionPerformed

    private void btn_clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseEntered
        Color clr = new Color(56,149,242);
        btn_cl.setBackground(clr);
    }//GEN-LAST:event_btn_clMouseEntered

    private void btn_clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseExited
        Color clr = new Color(52,151,217);
        btn_cl.setBackground(clr);
    }//GEN-LAST:event_btn_clMouseExited

    private void btn_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clActionPerformed
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_clActionPerformed

    private void btn_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseEntered
        Color clr = new Color(56,149,242);
        btn_b.setBackground(clr);
    }//GEN-LAST:event_btn_bMouseEntered

    private void btn_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseExited
        Color clr = new Color(52,151,217);
        btn_b.setBackground(clr);
    }//GEN-LAST:event_btn_bMouseExited

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_lMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseEntered
        Color clr = new Color(56,149,242);
        btn_l.setBackground(clr);
    }//GEN-LAST:event_btn_lMouseEntered

    private void btn_lMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseExited
        Color clr = new Color(52,151,217);
        btn_l.setBackground(clr);
    }//GEN-LAST:event_btn_lMouseExited

    private void btn_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lActionPerformed
        LogIn li = new LogIn();
        li.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_lActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilePathActionPerformed

    private void comboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCourseActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        clearTable();
        setRecordToTable();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String dateFrom = dateFormat.format(fromDate.getDate());
        String dateTo = dateFormat.format(toDate.getDate());
        MessageFormat header = new MessageFormat("Report From"+dateFrom+" to "+dateTo);
        MessageFormat footer = new MessageFormat("Page(0,number,integer)");
        
        try{
            tblViewReport.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }
        catch(Exception e){
            e.getMessage();
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String date = dateFormat.format(new Date());
        try{
            File f = fileChooser.getSelectedFile();
            String path = f.getAbsolutePath();
            
            path = path+" "+date+".xlsx";
            txtFilePath.setText(path);
        }
        catch(Exception e){
            e.getMessage();
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btn_clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseClicked
      
    }//GEN-LAST:event_btn_clMouseClicked

    public void exportToExcel(){
//        XSSFWorkbook wb = new XSSFWorkbook();
////        XSSFSheet ws = wb.createSeet();
//        DefaultTableModel model = (DefaultTableModel)tblViewReport.getModel();
//        
//        TreeMap<String, Object[]> map = new TreeMap<>();
//        
//        map.put("0", new Object[]{model.getColumnName(0), model.getColumnName(1),model.getColumnName(2), model.getColumnName(3),
//            model.getColumnName(4),model.getColumnName(5),model.getColumnName(6)});
//        
//        for(int i = 1; i<model.getRowCount(); i++){
//            map.put(Integer.toString(i), Object[]{model.getValueAt(i,0), model.getValueAt(i, 1), model.getValueAt(i, 2), 
//            model.getValueAt(i, 3), model.getValueAt(i, 4), model.getValueAt(i, 5), model.getValueAt(i, 6)});
//        }
//        
//        Set<String> id = map.keySet();
//        XSSFROW frow;
//        
//        int rowId = 0;
//       
//        for(Map.Entry<String, Object[]> entry : map.entrySet()){
//            String key = entry.getKey();
//            Object[] value = entry.getValue();
//            System.out.println("Value");
//        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_cl;
    private javax.swing.JButton btn_ec;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_l;
    private javax.swing.JButton btn_sr;
    private javax.swing.JComboBox<String> comboCourse;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel selectedCourse;
    private javax.swing.JTable tblViewReport;
    private com.toedter.calendar.JDateChooser toDate;
    private javax.swing.JLabel totalAmountCollect;
    private javax.swing.JLabel totalAmountInWord;
    private javax.swing.JTextField txtFilePath;
    // End of variables declaration//GEN-END:variables
}
