/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajan
 */
public class ViewAllRecord extends javax.swing.JFrame {

    DefaultTableModel model = null;
    
    public ViewAllRecord() {
        initComponents();
        setRecordToTable();
    }
    
    public void setRecordToTable(){
        try{
            Connection con = DBConnection.getMysqlConnection();
            PreparedStatement pst = con.prepareStatement("Select * from fees_details");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String recieptNo = rs.getString("reciept_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("course_name");
                String paymentMode = rs.getString("payment_mode");
                String amount = rs.getString("total_amount");
                String date = rs.getDate("date").toString();
                String remark = rs.getString("remarks");
                
                Object[] obj = {recieptNo, rollNo, studentName, courseName, paymentMode, amount, date, remark};
                
                model = (DefaultTableModel)tblRecords.getModel();
                model.addRow(obj);
                
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_sr = new javax.swing.JButton();
        btn_ec = new javax.swing.JButton();
        btn_cl = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_l = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 151, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(52, 151, 219));
        btn_home.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), null, null, new java.awt.Color(0, 102, 255)));
        btn_home.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 260, 70));

        btn_sr.setBackground(new java.awt.Color(52, 151, 219));
        btn_sr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_sr.setForeground(new java.awt.Color(255, 255, 255));
        btn_sr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/search2.png"))); // NOI18N
        btn_sr.setText("Search Record");
        btn_sr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_sr.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_sr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_srMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_srMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_srMouseExited(evt);
            }
        });
        btn_sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_srActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 260, 70));

        btn_ec.setBackground(new java.awt.Color(52, 151, 219));
        btn_ec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_ec.setForeground(new java.awt.Color(255, 255, 255));
        btn_ec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/edit2.png"))); // NOI18N
        btn_ec.setText("Edit Course");
        btn_ec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_ec.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_ec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ecMouseExited(evt);
            }
        });
        btn_ec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ecActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 260, 70));

        btn_cl.setBackground(new java.awt.Color(52, 151, 219));
        btn_cl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_cl.setForeground(new java.awt.Color(255, 255, 255));
        btn_cl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/list_1.png"))); // NOI18N
        btn_cl.setText("Course List");
        btn_cl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_cl.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clMouseExited(evt);
            }
        });
        btn_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 260, 70));

        btn_b.setBackground(new java.awt.Color(52, 151, 219));
        btn_b.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_b.setForeground(new java.awt.Color(255, 255, 255));
        btn_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/left-arrow.png"))); // NOI18N
        btn_b.setText("Back");
        btn_b.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_b.setMargin(new java.awt.Insets(0, -10, 1, 25));
        btn_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bMouseExited(evt);
            }
        });
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });
        jPanel1.add(btn_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 260, 70));

        btn_l.setBackground(new java.awt.Color(52, 151, 219));
        btn_l.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_l.setForeground(new java.awt.Color(255, 255, 255));
        btn_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/logout.png"))); // NOI18N
        btn_l.setText("Log Out");
        btn_l.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), null, null, new java.awt.Color(0, 102, 255)));
        btn_l.setMargin(new java.awt.Insets(0, 0, 1, 5));
        btn_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lMouseExited(evt);
            }
        });
        btn_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lActionPerformed(evt);
            }
        });
        jPanel1.add(btn_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 260, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/image/back1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 770));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRecords.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reciept No.", "Roll No.", "Student Name", "Course Name", "Payment Mode", "Amount", "Date", "Remark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRecords);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 950, 600));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Records");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 950, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 990, 770));

        setSize(new java.awt.Dimension(1402, 774));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        Color clr = new Color(56,149,242);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        Color clr = new Color(52,151,217);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_srMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseEntered
        Color clr = new Color(56,149,242);
        btn_sr.setBackground(clr);
    }//GEN-LAST:event_btn_srMouseEntered

    private void btn_srMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseExited
        Color clr = new Color(52,151,217);
        btn_sr.setBackground(clr);
    }//GEN-LAST:event_btn_srMouseExited

    private void btn_srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_srActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_srActionPerformed

    private void btn_ecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseEntered
        Color clr = new Color(56,149,242);
        btn_ec.setBackground(clr);
    }//GEN-LAST:event_btn_ecMouseEntered

    private void btn_ecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseExited
        Color clr = new Color(52,151,217);
        btn_ec.setBackground(clr);
    }//GEN-LAST:event_btn_ecMouseExited

    private void btn_ecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ecActionPerformed

    private void btn_clMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseEntered
        Color clr = new Color(56,149,242);
        btn_cl.setBackground(clr);
    }//GEN-LAST:event_btn_clMouseEntered

    private void btn_clMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clMouseExited
        Color clr = new Color(52,151,217);
        btn_cl.setBackground(clr);
    }//GEN-LAST:event_btn_clMouseExited

    private void btn_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clActionPerformed
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_clActionPerformed

    private void btn_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseEntered
        Color clr = new Color(56,149,242);
        btn_b.setBackground(clr);
    }//GEN-LAST:event_btn_bMouseEntered

    private void btn_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseExited
        Color clr = new Color(52,151,217);
        btn_b.setBackground(clr);
    }//GEN-LAST:event_btn_bMouseExited

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_lMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseEntered
        Color clr = new Color(56,149,242);
        btn_l.setBackground(clr);
    }//GEN-LAST:event_btn_lMouseEntered

    private void btn_lMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseExited
        Color clr = new Color(52,151,217);
        btn_l.setBackground(clr);
    }//GEN-LAST:event_btn_lMouseExited

    private void btn_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lActionPerformed
        LogIn li = new LogIn();
        li.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_lActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_srMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srMouseClicked
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_srMouseClicked

    private void btn_ecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ecMouseClicked
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_cl;
    private javax.swing.JButton btn_ec;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_l;
    private javax.swing.JButton btn_sr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRecords;
    // End of variables declaration//GEN-END:variables
}
